/* Body file for function Observation_Timeline_Implementation
 * Generated by TASTE on 2019-11-28 14:05:03
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Execute
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 108642 70312 146384 87126
 * Timers              : 
 */

#include "observation_timeline_implementation.h"
//#include <stdio.h>

/* Include Context Parameters (constants defined in the Interface View) */
#include "Context-observation-timeline-implementation.h"

void observation_timeline_implementation_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[Observation_Timeline_Implementation] Startup");
}

void observation_timeline_implementation_PI_Execute
      (const asn1SccT_Int32 *IN_inp,
       asn1SccT_Int32 *OUT_outp)

{
   *OUT_outp = *IN_inp + 1;
}




