/* Body file for function helloworld2
 * Generated by TASTE on 2019-08-09 09:15:45
 * You can edit this file, it will not be overwritten
 * Provided interfaces : task2
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 152751 58267 185664 87242
 * Timers              : 
 */

#include "helloworld2.h"

#include <stdio.h>

void helloworld2_startup(void)
{
   puts ("[helloworld2] Call from partition containing task 2 (startup)");
}

void helloworld2_PI_task2(void)
{
   puts ("[helloworld2] Tick");
}



