/* Body file for function helloworld1
 * Generated by TASTE on 2019-08-09 09:15:45
 * You can edit this file, it will not be overwritten
 * Provided interfaces : task1
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 83777 59369 116690 88344
 * Timers              : 
 */

#include "helloworld1.h"
#include <stdio.h>

void helloworld1_startup(void)
{
   puts ("[helloworld1] Call from partition containing task 1 (startup)");
}

void helloworld1_PI_task1(void)
{
   puts ("[helloworld1] Tock");
}



