
/* Header file for function Function1 in C language
 * Generated by TASTE on 2020-04-29 14:12:57
 * Context Parameters present : NO
 * Provided interfaces : done, plastic
 * Required interfaces : doSth
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 96218 58581 124563 82518
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void function1_startup(void);

/* Provided interfaces */
void function1_PI_done( void );
void function1_PI_plastic( void );

/* Required interfaces */
extern void function1_RI_doSth( void );


#ifdef __cplusplus
}
#endif
