/* Body file for function Function1
 * Generated by TASTE on 2020-02-10 09:21:12
 * You can edit this file, it will not be overwritten
 * Provided interfaces : done, plastic
 * Required interfaces : doSth
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 96218 58581 124563 82518
 * Timers              : 
 */

#include "function1.h"
#include <stdio.h>


void function1_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
    puts ("[Function1] Startup");
    //function1_RI_doSth();
}

void function1_PI_done(void)
{
   // Write your code here
    puts("done");
}


void function1_PI_plastic(void)
{
   // Write your code here
    puts("hello");
}




