/* Body file for function slave
 * Generated by TASTE on 2020-02-19 15:23:19
 * You can edit this file, it will not be overwritten
 * Provided interfaces : you_are_free
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 138388 61493 173779 87242
 * Timers              : 
 */

#include "slave.h"
#include <stdio.h>


void slave_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   puts ("[slave] Startup");
}

void slave_PI_you_are_free(void)
{
    static int count = 0;
    if (0 == count) {
       puts("[slave] I am free? Really? I don't believe it");
       count ++;
    }
    else {
        puts("[slave] Second call, I say thank you");
        slave_RI_Thank_you();
    }
}




