// Body file for function Function2
// Generated by TASTE on 2019-11-19 15:29:01
// You can edit this file, it will not be overwritten
// Provided interfaces : doSomethingInCPP
// Required interfaces : 
// User-defined properties for this function:
//   |_ Taste::Active_Interfaces = any
//   |_ Taste::coordinates = 151807 59211 191176 105981
// Timers              : 

#include "function2.h"
#include "function2_state.h"
#include <iostream>

// Define and use function state inside this context structure
// avoid defining global/static variable elsewhere
function2_state ctxt;


void function2_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[Function2] Startup");
}

void function2_PI_doSomethingInCPP
      (const asn1SccT_Int32 *IN_in1,
       asn1SccT_Int32 *OUT_out1)

{
    std::cout << *IN_in1 << std::endl;
    *OUT_out1 = *IN_in1 + ctxt.counter;
}




