/* Body file for function Scene_Creation_Implementation
 * Generated by TASTE on 2019-11-28 14:05:03
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Execute_Module2
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 165314 122869 203056 139683
 * Timers              : 
 */

#include "scene_creation_implementation.h"
//#include <stdio.h>

/* Include Context Parameters (constants defined in the Interface View) */
#include "Context-scene-creation-implementation.h"

void scene_creation_implementation_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[Scene_Creation_Implementation] Startup");
}

void scene_creation_implementation_PI_Execute
      (const asn1SccT_Int32 *IN_inp,
       asn1SccT_Int32 *OUT_outp)

{
   *OUT_outp = *IN_inp + scene_creation_implementation_ctxt.scene_model_data;
}




