/* Body file for function Gnc
 * Generated by TASTE on 2020-01-08 15:23:27
 * You can edit this file, it will not be overwritten
 * Provided interfaces : do_something
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 168500 62527 230065 103086
 * Timers              : 
 */

#include "gnc.h"
//#include <stdio.h>


void gnc_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
    printf("\n[gnc_startup] Starting up ...\n");
}

void gnc_PI_do_something
      (const asn1SccSeq3 *IN_inp1,
       const asn1SccSeq3 *IN_inp2,
       const asn1SccSeq4 *IN_inp3,
       asn1SccSeqout *OUT_outpu,
       const asn1SccIn_Nested *IN_innested,
       asn1SccOut_Nested *OUT_outnested)

{
   // Write your code here
    printf("[gnc_PI_do_something] Start\n");

    asn1SccT_Int32 rtb_Sum2;
    asn1SccT_Int32 rtb_Sum2_idx_0;
    asn1SccT_Int32 rtb_Sum2_idx_1;
    asn1SccT_Int32 rtb_Sum2_idx_2;

  /* Sum: '<Root>/Sum2' incorporates:
   *  Gain: '<Root>/Gain2'
   *  Inport: '<Root>/innested'
   *  Inport: '<Root>/inp3'
   */
  rtb_Sum2 = 5 * IN_inp3->arr[0] +
    IN_innested->inest_a.arr[0];

  /* Outport: '<Root>/outpu' incorporates:
   *  Inport: '<Root>/inp3'
   *  SignalConversion: '<Root>/TmpSignal ConversionAtoutpu_Seqout_BusCreInport1'
   */
  OUT_outpu->arr[0] = IN_inp3->arr[0];
  OUT_outpu->arr[4] = rtb_Sum2;

  /* Sum: '<Root>/Sum2' incorporates:
   *  Gain: '<Root>/Gain2'
   *  Inport: '<Root>/innested'
   *  Inport: '<Root>/inp3'
   */
  rtb_Sum2_idx_0 = rtb_Sum2;
  rtb_Sum2 = 5 * IN_inp3->arr[1] +
    IN_innested->inest_a.arr[1];

  /* Outport: '<Root>/outpu' incorporates:
   *  Inport: '<Root>/inp3'
   *  SignalConversion: '<Root>/TmpSignal ConversionAtoutpu_Seqout_BusCreInport1'
   */
  OUT_outpu->arr[1] = IN_inp3->arr[1];
  OUT_outpu->arr[5] = rtb_Sum2;

  /* Sum: '<Root>/Sum2' incorporates:
   *  Gain: '<Root>/Gain2'
   *  Inport: '<Root>/innested'
   *  Inport: '<Root>/inp3'
   */
  rtb_Sum2_idx_1 = rtb_Sum2;
  rtb_Sum2 = 5 * IN_inp3->arr[2] +
    IN_innested->inest_a.arr[2];

  /* Outport: '<Root>/outpu' incorporates:
   *  Inport: '<Root>/inp3'
   *  SignalConversion: '<Root>/TmpSignal ConversionAtoutpu_Seqout_BusCreInport1'
   */
  OUT_outpu->arr[2] = IN_inp3->arr[2];
  OUT_outpu->arr[6] = rtb_Sum2;

  /* Sum: '<Root>/Sum2' incorporates:
   *  Gain: '<Root>/Gain2'
   *  Inport: '<Root>/innested'
   *  Inport: '<Root>/inp3'
   */
  rtb_Sum2_idx_2 = rtb_Sum2;
  rtb_Sum2 = 5 * IN_inp3->arr[3] +
    IN_innested->inest_a.arr[3];

  /* Outport: '<Root>/outpu' incorporates:
   *  Inport: '<Root>/inp3'
   *  SignalConversion: '<Root>/TmpSignal ConversionAtoutpu_Seqout_BusCreInport1'
   */
  OUT_outpu->arr[3] = IN_inp3->arr[3];
  OUT_outpu->arr[7] = rtb_Sum2;

  /* Outport: '<Root>/outnested' incorporates:
   *  Gain: '<Root>/Gain'
   *  Gain: '<Root>/Gain1'
   *  Inport: '<Root>/innested'
   *  Inport: '<Root>/inp1'
   *  Inport: '<Root>/inp2'
   *  SignalConversion: '<Root>/TmpSignal ConversionAtoutpu_Seqout_BusCre1Inport1'
   *  Sum: '<Root>/Sum'
   *  Sum: '<Root>/Sum1'
   */
  OUT_outnested->onest_a.arr[0] = (6 *
    IN_inp1->arr[0] + IN_inp2->arr[0]) +
    3 * IN_innested->inest_b.arr[0];
  OUT_outnested->onest_a.arr[1] = (6 *
    IN_inp1->arr[1] + IN_inp2->arr[1]) +
    3 * IN_innested->inest_b.arr[1];
  OUT_outnested->onest_a.arr[2] = (6 *
    IN_inp1->arr[2] + IN_inp2->arr[2]) +
    3 * IN_innested->inest_b.arr[2];
  OUT_outnested->onest_a.arr[3] = rtb_Sum2_idx_0;
  OUT_outnested->onest_a.arr[4] = rtb_Sum2_idx_1;
  OUT_outnested->onest_a.arr[5] = rtb_Sum2_idx_2;
  OUT_outnested->onest_a.arr[6] = rtb_Sum2;
  
}




