--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
with Taste_Dataview;   use Taste_Dataview;
with Taste_Basictypes; use Taste_Basictypes;

package Memoryscrub_RI is

   

end Memoryscrub_RI;
