/* C++ Body file for function type Father
 * Generated by TASTE on 2019-11-19 12:52:54
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Pulse
 * Required interfaces : DoSomething
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 131020 52282 162515 69604
 *   |_ Taste::is_Component_Type = true
 * Timers              : 
 */

#include "father.h"
#include <stdio.h>

void father::startup()
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   puts ("[C++] Startup");
}

void father::Pulse(void)
{
   RI_DoSomething(&ctxt.a, &ctxt.b);
   printf("[C++] %lld\n",ctxt.b );
   ctxt.a++;
   RI_pong();
}

void father::ping(const asn1SccT_Boolean *val)
{
   printf("[C++] %s\n", *val ? "Ping":"Pong");
}



