/* Body file for function GNC
 * Generated by TASTE on 2019-07-14 08:11:44
 * You can edit this file, it will not be overwritten
 * Provided interfaces : guidance
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 142673 57006 169917 79368
 * Timers              : 
 */

#include "gnc.h"
#include <stdio.h>

void gnc_startup()
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   puts ("[GNC] Startup");
}

void gnc_PI_guidance
      (const asn1SccT_UInt32 *IN_a,
       asn1SccT_Boolean *OUT_result)
{
    puts("[GNC] Guidance function called");
    *OUT_result = (42 == *IN_a);
}

void gnc_PI_get_pro_data(asn1SccT_Boolean *OUT_outp)
{
    puts("[GNC] get_pro_data called");
    static asn1SccT_Boolean toggle = false;
    *OUT_outp = toggle;
    toggle = toggle ? false : true;
}
void gnc_PI_gnc_async( const asn1SccT_Int32 *a)
{
    printf("[GNC] ASync data call: %lld\n", *a);
}
