--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
with Taste_Dataview;   use Taste_Dataview;
with Taste_Basictypes; use Taste_Basictypes;

package Orchestrator_RI is

   procedure Computegnc (Inp : in out asn1SccMyinteger; Outp : out asn1SccMyinteger)
      with Import,
           Convention => C,
           Link_Name  => "orchestrator_RI_computeGNC";
   procedure Housekeeping (Hk : in out asn1SccMyinteger)
      with Import,
           Convention => C,
           Link_Name  => "orchestrator_RI_housekeeping";

end Orchestrator_RI;
