
/* Header file for function passiveFunction in C language
 * Generated by TASTE on 2020-09-18 15:20:12
 * Context Parameters present : NO
 * Provided interfaces : computeGNC
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::coordinates = 1920 1180 2607 1814
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void passivefunction_startup(void);

/* Provided interfaces */
void passivefunction_PI_computeGNC( const asn1SccMyInteger *, asn1SccMyInteger * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
