// Body file for function Function1
// Generated by TASTE on 2020-06-19 15:39:18
// You can edit this file, it will not be overwritten
// Provided interfaces : pulse
// Required interfaces : doSomethingInCPP
// User-defined properties for this function:
//   |_ Taste::Active_Interfaces = any
//   |_ Taste::coordinates = 88187 56534 124879 110076
// Timers              : 

#include "function1.h"
#include "function1_state.h"
//#include <iostream>

// Define and use function state inside this context structure
// avoid defining global/static variable elsewhere
function1_state ctxt_function1;
extern int Bar(void);

void function1_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // std::cout << "[Function1] Startup" << std::endl;
   Bar();
}

void function1_PI_pulse(void)
{
   // Write your code here
}


