--  Body file for function Function_in_Ada
--  Generated by TASTE on 2019-10-06 11:17:27
--  You can edit this file, it will not be overwritten
--  Provided interfaces : run_ada
--  Required interfaces : 
--  Timers              : 

--  Include Context Parameters (constants defined in the Interface View) */
with Context_Function_In_Ada;
use Context_Function_In_Ada;
with system.io;
use system.io;

package body Function_In_Ada is

   procedure Run_Ada is

   begin
      --  Write your code here
      null;
   end Run_Ada;


   begin
      Put ("[Ada] Startup: ");
      Put_Line (function_in_ada_ctxt.ada1'img & " " & function_in_ada_ctxt.ada2'img);

end Function_In_Ada;

