--  Body file for function GeometryModule_Implementation
--  Generated by TASTE on 2019-11-28 14:15:29
--  You can edit this file, it will not be overwritten
--  Provided interfaces : Execute
--  Required interfaces : 
--  Timers              : 

--  Include Context Parameters (constants defined in the Interface View) */
--  with Context....geometrymodule-implementation;
with interfaces; use interfaces;

with Context_geometrymodule_implementation;
use Context_geometrymodule_implementation;

package body Geometrymodule_Implementation is

   procedure Execute (inp : in out asn1SccT_Int32; outp : out asn1SccT_Int32) is

   begin
      --  Write your code here
      outp := inp + geometrymodule_implementation_ctxt.orbit_and_time_params;
   end Execute;



   begin
      --  Write your startup code here
      null;

end Geometrymodule_Implementation;

