/* Body file for function Function2
 * Generated by TASTE on 2020-04-28 13:58:47
 * You can edit this file, it will not be overwritten
 * Provided interfaces : adder
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 138264 60156 167397 91808
 *   |_ TASTE_IV_Properties::FPGA_Configurations = AllModes
 * Timers              : 
 */

#include "function2.h"
//#include <stdio.h>


void function2_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[Function2] Startup");
}

void function2_PI_adder
      (const asn1SccT_Int32 *IN_inp,
       asn1SccT_Int32 *OUT_outp)

{
   // Write your code here
    if( *IN_inp % 2 == 0){
        *OUT_outp = 2;
        return;
    } else {
        for (int i=3; i <= *IN_inp / 2; i+=2){
            if(0 == (*IN_inp %i)){
                *OUT_outp = i;
                return;
            }
        }
    }
    *OUT_outp = *IN_inp;
}


