--  Body file for function Simple_Ada
--  Generated by TASTE on 2020-01-04 10:04:13
--  You can edit this file, it will not be overwritten
--  Provided interfaces : Pulse
--  Required interfaces : 
--  Timers              : 

with System.IO;
package body Simple_Ada is

   procedure Pulse is

   begin
      System.IO.Put_Line("Ping");
   end Pulse;



   begin
      System.IO.Put_Line("This line must appear at startup");

end Simple_Ada;

