/* Body file for function Function3
 * Generated by TASTE on 2020-02-05 16:31:59
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Float_to_String
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 1354 27 2011 339
 * Timers              : 
 */

#include <stdio.h>
#include <string.h>
#include "function3.h"


void function3_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[Function3] Startup");
}

void function3_PI_Float_to_String
      (const asn1SccTFloat *IN_inp,
       asn1SccDebug_PrintableString *OUT_outp)

{
   sprintf(OUT_outp->arr, "OUT: %f\n", *IN_inp);
   OUT_outp->nCount = (int)strlen(OUT_outp->arr);
}




